services:
  web:
    build: .
    image: ${APP_IMAGE}
    depends_on:
      - "redis"
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=${REDIS_HOST}

  redis:
    image: "redis:alpine"
